### ISSUE TITLE
inner product in the code?

### ISSUE THREAD

**Issue by tsengalb99** [nikhilvyas/SOAP#16]
Line 3 of Algorithm 3 in the paper conjugates G by QL and QR. However, the code only seems to keep track of GG^T and L (outer_product) and not G^T G and R. Where is G^T G computed in the code?

**Comment by nikhilvyas** [comment]
state['GG'] is a list which maintains both GG^T and G^TG.

**Comment by jie040109** [comment]
> state['GG'] is a list which maintains both GG^T and G^TG.

It seems that this is not reflected in the code
