### ISSUE TITLE
foreach implementation?

### ISSUE THREAD

**Issue by neosr-project** [nikhilvyas/SOAP#19]
Hi, thanks for your research. I have successfully used SOAP for [training image restoration networks](https://github.com/neosr-project/neosr/blob/dev/neosr/optimizers/soap.py). However, while it works very well, performance is not great as I'm sure contributors are aware. Are there any plans to release a `foreach` version of SOAP? It would make it usable in real world scenarios for my user case. I've previously [ported schedule-free to adan `foreach`](https://github.com/neosr-project/adan_schedule_free), so I might be able to help in some way or another, even though I'm not a researcher in the field.
Thanks in advance.

**Comment by nikhilvyas** [comment]
There is a foreach implementation by Lucas Nestler at https://github.com/ClashLuke/HeavyBall. We are planning to update our implementation to also have it. I will also mention the biggest blocker to performance is better QR decomposition (Pytorch and Cusolver only support fp32 format making it slower).
