### ISSUE TITLE
Why compute eigenbases before accumulating GG' and G'G?

### ISSUE THREAD

**Issue by jondeuce** [nikhilvyas/SOAP#6]
I'm curious as to why in [Algorithm 3 in your paper](https://arxiv.org/abs/2409.11321) you compute the eigenbases `QL` and `QR` before updating the moving averages `L = beta2 * L + (1 - beta2) * G * G'`  and `R = beta2 * R + (1 - beta2) * G' * G`. Typically second-order statistics accumulators are updated before computing the update step (e.g. both Shampoo and Adafactor which this method is based on, as well as Adagrad, Adam, etc.).

It is even [mentioned in the code](https://github.com/nikhilvyas/SOAP/blob/fd71829b3fb04b2af9324b2fed1f8c6b9cc3b478/soap.py#L144) that this was a deliberate choice, but I can't find anything discussed in the paper, so I'm curious if it was an empirical finding or if there is a theoretical reason. I've implemented SOAP with both pre- and post-step updating of the `L` and `R` factors and have not noticed any difference, but maybe you have.

Btw, the algorithm works amazingly well, better than Adam, Schedule-free Adam, and Shampoo on a fairly heavily-tuned variational inference problem I've been working on for a while now, so congratulations on the great work!

**Comment by nikhilvyas** [comment]
Thanks! It would be great to see your results (you could perhaps post them in the "Discussions" section of github) whenever you are ready to make them public.

We found it to work better (or be more stable wrt other hyperparameters) at preconitioning frequency 1, for larger frequeuncies it does not make a difference. Another way to see this is that if at the the first step we used the gradients to compute L, R, Q_L, Q_R then the first step gradient (G) after projection in the Q_L, Q_R basis would become a diagonal matrix and then the Adam exp_avg_sq would be 0 for non-diagonal entries. This is numerically unstable (if not for eps) which is not a good situation to be in. Will try to add some experiments about this in the next version.

**Comment by jondeuce** [comment]
Ahh, thanks for the explanation, that makes perfect sense. I see now that apart from the first step, in general G will not be exactly diagonalized by the transformation to Shampoo's eigenspace and so V will be nonzero everywhere by the second step. I suppose that increasing epsilon to e.g. sqrt(machine eps) would also help to mitigate the issue, but I agree it's cleaner to just skip the first step.

And sounds good, I'd be happy to share my results when they're ready; in the process of writing the paper currently.
