### ISSUE TITLE
I encountered the following difficulties when running the Soap optimizer based on GaLore's official code: https://github.com/jiaweizzhao/GaLore/tree/master

### ISSUE THREAD

**Issue by jie040109** [nikhilvyas/SOAP#9]
:2193760:2193760 [0] NCCL INFO AllGather: opCount 109a2 sendbuff 0x7f76851d0400 recvbuff 0x7f76851d0800 count 4 datatype 0 op 0 root 0 comm 0x1f3e8500 [nranks=2] stream 0x2075530
:2193760:2193760 [0] NCCL INFO 8 Bytes -> Algo 1 proto 0 time 7.601200
[rank1]:[E1029 15:09:04.069887196 ProcessGroupNCCL.cpp:607] [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=68002, OpType=ALLGATHER, NumelIn=1, NumelOut=2, Timeout(ms)=600000) ran for 600033 milliseconds before timing out.
[rank1]:[E1029 15:09:04.070723079 ProcessGroupNCCL.cpp:1664] [PG 0 (default_pg) Rank 1] Exception (either an error or timeout) detected by watchdog at work: 68002, last enqueued NCCL work: 68002, last completed NCCL work: 68001.
:2193761:2199866 [1] NCCL INFO [Service thread] Connection closed by localRank 1
:2193761:2199867 [1] NCCL INFO [Proxy Service UDS] exit: stop 1 abortFlag 1
:2193761:2194087 [1] NCCL INFO comm 0x6e0a0ec0 rank 1 nranks 2 cudaDev 1 busId 57000 - Abort COMPLETE
[rank1]:[E1029 15:09:04.663804096 ProcessGroupNCCL.cpp:1709] [PG 0 (default_pg) Rank 1] Timeout at NCCL work: 68002, last enqueued NCCL work: 68002, last completed NCCL work: 68001.
[rank1]:[E1029 15:09:04.663829684 ProcessGroupNCCL.cpp:621] [Rank 1] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[rank1]:[E1029 15:09:04.663840871 ProcessGroupNCCL.cpp:627] [Rank 1] To avoid data inconsistency, we are taking the entire process down.
[rank1]:[E1029 15:09:04.666191552 ProcessGroupNCCL.cpp:1515] [PG 0 (default_pg) Rank 1] Process group watchdog thread terminated with exception: [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=68002, OpType=ALLGATHER, NumelIn=1, NumelOut=2, Timeout(ms)=600000) ran for 600033 milliseconds before timing out.
Exception raised from checkTimeout at ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:609 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x7f3813e21f86 in /home/jjwang/miniconda3/envs/GaLore/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: c10d::ProcessGroupNCCL::WorkNCCL::checkTimeout(std::optional<std::chrono::duration<long, std::ratio<1l, 1000l> > >) + 0x1d2 (0x7f381511e8f2 in /home/jjwang/miniconda3/envs/GaLore/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #2: c10d::ProcessGroupNCCL::watchdogHandler() + 0x233 (0x7f3815125333 in /home/jjwang/miniconda3/envs/GaLore/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #3: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x10c (0x7f381512771c in /home/jjwang/miniconda3/envs/GaLore/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #4: <unknown function> + 0xdbbf4 (0x7f386285fbf4 in /home/jjwang/miniconda3/envs/GaLore/bin/../lib/libstdc++.so.6)
frame #5: <unknown function> + 0x8609 (0x7f3867b02609 in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #6: clone + 0x43 (0x7f38678cd353 in /lib/x86_64-linux-gnu/libc.so.6)

W1029 15:09:05.731221 140718453052608 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 2193760 closing signal SIGTERM
E1029 15:09:06.558402 140718453052608 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: -6) local_rank: 1 (pid: 2193761) of binary: /home/jjwang/miniconda3/envs/GaLore/bin/python
Traceback (most recent call last):
  File "/home/jjwang/miniconda3/envs/GaLore/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/jjwang/miniconda3/envs/GaLore/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 348, in wrapper
    return f(*args, **kwargs)
  File "/home/jjwang/miniconda3/envs/GaLore/lib/python3.8/site-packages/torch/distributed/run.py", line 901, in main
    run(args)
  File "/home/jjwang/miniconda3/envs/GaLore/lib/python3.8/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/home/jjwang/miniconda3/envs/GaLore/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/jjwang/miniconda3/envs/GaLore/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 

torchrun_main.py FAILED

Failures:
  <NO_OTHER_FAILURES>

Root Cause (first observed failure):
[0]:
  time      : 2024-10-29_15:09:05
  rank      : 1 (local_rank: 1)
  exitcode  : -6 (pid: 2193761)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 2193761

**Comment by nikhilvyas** [comment]
This codebase is for single gpu runs, we plan to add multi gpu code soon.
